# Generated by Django 2.2.3 on 2019-09-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('magers', models.CharField(blank=True, max_length=15000, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('tel', models.IntegerField(blank=True, max_length=13, null=True)),
                ('resome', models.CharField(max_length=15000)),
                ('master_price', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.CharField(blank=True, max_length=15000, null=True)),
                ('courses', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
